### ISSUE TITLE
LMDB No locks available

### ISSUE THREAD

**Issue by flauted** [flauted/coco-caption#2]
The SPICE metric can fail in certain cases.
```
Parsing reference captions
Error: Could not score batched file input:
org.fusesource.lmdbjni.LMDBException: No locks available
        at org.fusesource.lmdbjni.Util.checkErrorCode(Util.java:44)
        at org.fusesource.lmdbjni.Env.open(Env.java:192)
        at org.fusesource.lmdbjni.Env.open(Env.java:72)
        at org.fusesource.lmdbjni.Env.open(Env.java:65)
        at edu.anu.spice.LmdbTupleDB.getTransaction(LmdbTupleDB.java:93)
        at edu.anu.spice.SpiceParser.loadTuplesFromDB(SpiceParser.java:195)
        at edu.anu.spice.SpiceParser.loadTuples(SpiceParser.java:245)
        at edu.anu.spice.SpiceParser.parseCaptions(SpiceParser.java:251)
        at edu.anu.spice.SpiceScorer.scoreBatch(SpiceScorer.java:109)
        at edu.anu.spice.SpiceScorer.main(SpiceScorer.java:60)
```
...
```
subprocess.CalledProcessError: Command '['java', '-jar', '-Xmx8G', 'spice-1.0.jar', '...pycocoevalcap/spice/tmp/tmpnt_dwdqn', '-cache', '...pycocoevalcap/spice/cache', '-out', '...pycocoevalcap/spice/tmp/tmpspx0hvw9', '-subset', '-silent']' returned non-zero exit status 1.
```
where `...` is on an NFS mount.

**Comment by flauted** [comment]
[This](https://askubuntu.com/questions/837962/nfs-error-no-locks-available-after-update-to-16-10) has a suggested fix IF you're a sudoer.

More to the point: [This](https://github.com/BD2KGenomics/protect/issues/70) issue suggests it probably is related to caching on an NFS server (although it doesn't mention LMDB).

**Comment by flauted** [comment]
Use the environment variables ``SPICE_CACHE_DIR`` and ``SPICE_TEMP_DIR`` to point the cache to somewhere off of the NFS mount.
